routes:
  - name: Session Incoming
    userPath: session/incoming
    brokerPath: session/incoming/{{player}}
    type: queue
    direction: incoming

  # - name: Session Outgoing
  #   brokerPath: session/outgoing/{{player}}
  #   type: queue
  #   direction: outgoing

  # - name: Matchmaking Find
  #   path: matchmaking/find/
  #   type: stream
  #   direction: incoming
  #   schema: |
  #     {
  #         "type": "object",
  #         "properties": {
  #             "username": {
  #                 "type": "string",
  #                 "minLength": 1
  #             }
  #         }
  #     }

  # - name: Matchmaking Invite
  #   path: matchmaking/invite
  #   type: stream
  #   direction: incoming
  #   schema: |
  #     {
  #         "type": "object",
  #         "properties": {
  #             "sourceUsername": {
  #                 "type": "string",
  #                 "minLength": 1
  #             },
  #             "destinationUsername": {
  #                 "type": "string",
  #                 "minLength": 1
  #             }
  #         }
  #     }

  # - name: Match Results
  #   path: results
  #   type: stream
  #   direction: outgoing
