routes:
  - name: Session Incoming
    userPrefix: session/incoming/
    brokerPath: session/incoming/{{player}}
    type: queue
    direction: incoming

  - name: Session Outgoing
    userPrefix: none
    brokerPath: session/outgoing/{{player}}
    type: queue
    direction: outgoing

  - name: Matchmaking Invite
    userPrefix: matchmaking/invite
    brokerPath: matchmaking/invite
    type: stream
    direction: incoming
    schema: |
      {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "type": "object",
          "properties": {
              "sourceUsername": {
                  "const": "{{player}}"
              },
              "destinationUsername": {
                  "type": "string",
                  "minLength": 1
              }
          },
          "required": ["sourceUsername", "destinationUsername"],
          "additionalProperties": false
      }

  # - name: Matchmaking Find
  #   path: matchmaking/find/
  #   type: stream
  #   direction: incoming
  #   schema: |
  #     {
  #         "type": "object",
  #         "properties": {
  #             "username": {
  #                 "type": "string",
  #                 "minLength": 1
  #             }
  #         }
  #     }

  # - name: Match Results
  #   path: results
  #   type: stream
  #   direction: outgoing
